/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Nunito', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        display: ['Playfair Display', 'Georgia', 'serif'],
        body: ['Nunito', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Boho palette
        terracotta: {
          50: '#fdf4ef',
          100: '#fbe6d6',
          200: '#f6c9ac',
          300: '#f0a577',
          400: '#e87d45',
          500: '#bf6a3a',
          600: '#a85a30',
          700: '#8c4a28',
          800: '#6f3b20',
          900: '#5a311b',
        },
        sage: {
          50: '#f3f8f2',
          100: '#e3efe1',
          200: '#c7dfc3',
          300: '#a8c5a0',
          400: '#7db88e',
          500: '#5a9a60',
          600: '#4a7d4e',
          700: '#3d6540',
          800: '#345136',
          900: '#2c432e',
        },
        cream: {
          50: '#fdfbf8',
          100: '#faf6f1',
          200: '#f3ece3',
          300: '#e8ddd0',
          400: '#d4c4ae',
          500: '#bfa88c',
          600: '#a08a6e',
          700: '#7a6e62',
          800: '#5c5348',
          900: '#3d2e1f',
        },
        blush: {
          50: '#fef5f2',
          100: '#fce8e2',
          200: '#f5cdc0',
          300: '#e8b4a2',
          400: '#d99580',
          500: '#c97a63',
          600: '#b3604a',
          700: '#944d3c',
          800: '#7a4034',
          900: '#66372e',
        },
        // KDP technical colors
        'kdp-success': 'hsl(var(--kdp-success))',
        'kdp-bleed': 'hsl(var(--kdp-bleed))',
        'kdp-trim': 'hsl(var(--kdp-trim))',
        'kdp-safe': 'hsl(var(--kdp-safe))',
        'safe-bleed': 'hsl(var(--safe-bleed))',
        'safe-trim': 'hsl(var(--safe-trim))',
        'safe-grid': 'hsl(var(--safe-grid))',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        'sm': '0 1px 2px rgba(139, 109, 71, 0.04)',
        'md': '0 2px 8px rgba(139, 109, 71, 0.06)',
        'lg': '0 4px 16px rgba(139, 109, 71, 0.08)',
        'xl': '0 8px 24px rgba(139, 109, 71, 0.1)',
        '2xl': '0 16px 48px rgba(139, 109, 71, 0.12)',
        'boho': '0 2px 12px rgba(191, 106, 58, 0.08)',
        'boho-lg': '0 8px 24px rgba(191, 106, 58, 0.12)',
        'boho-glow': '0 0 20px rgba(191, 106, 58, 0.15)',
      },
      spacing: {
        'elegant-xs': 'var(--spacing-xs)',
        'elegant-sm': 'var(--spacing-sm)',
        'elegant-md': 'var(--spacing-md)',
        'elegant-lg': 'var(--spacing-lg)',
        'elegant-xl': 'var(--spacing-xl)',
        'elegant-2xl': 'var(--spacing-2xl)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 6s ease-in-out infinite",
        "shimmer": "shimmer 3s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
}
