/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Image = IDL.Record({
  'id' : IDL.Text,
  'dpi' : IDL.Float64,
  'owner' : IDL.Principal,
  'path' : IDL.Text,
  'projectId' : IDL.Text,
  'uploaded' : IDL.Int,
  'pageId' : IDL.Opt(IDL.Text),
});
export const Dimensions = IDL.Record({
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const BleedSpec = IDL.Record({
  'top' : IDL.Float64,
  'left' : IDL.Float64,
  'bottom' : IDL.Float64,
  'right' : IDL.Float64,
});
export const MarginSpec = IDL.Record({
  'top' : IDL.Float64,
  'left' : IDL.Float64,
  'bottom' : IDL.Float64,
  'right' : IDL.Float64,
});
export const KDPValidation = IDL.Record({
  'errors' : IDL.Vec(IDL.Text),
  'trimSize' : Dimensions,
  'warnings' : IDL.Vec(IDL.Text),
  'bleed' : BleedSpec,
  'margin' : MarginSpec,
  'spineWidth' : IDL.Float64,
  'isValid' : IDL.Bool,
});
export const Size = IDL.Record({
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const Layout = IDL.Record({ 'size' : Size, 'position' : Position });
export const CoverElement = IDL.Record({
  'text' : IDL.Text,
  'layout' : Layout,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const SpineSpec = IDL.Record({
  'text' : IDL.Text,
  'width' : IDL.Float64,
});
export const CoverSpec = IDL.Record({
  'front' : CoverElement,
  'back' : CoverElement,
  'spine' : SpineSpec,
  'bleed' : BleedSpec,
  'dimensions' : Dimensions,
});
export const ProjectSettings = IDL.Record({
  'font' : IDL.Text,
  'margin' : IDL.Float64,
  'fontSize' : IDL.Float64,
  'lineSpacing' : IDL.Float64,
});
export const ImagePosition = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const TextPosition = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const PageLayout = IDL.Record({
  'imagePosition' : ImagePosition,
  'textPosition' : TextPosition,
});
export const Page = IDL.Record({
  'text' : IDL.Text,
  'pageNumber' : IDL.Nat,
  'layout' : PageLayout,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'kdpValidation' : KDPValidation,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'cover' : CoverSpec,
  'updatedAt' : IDL.Int,
  'story' : IDL.Text,
  'settings' : ProjectSettings,
  'pages' : IDL.Vec(Page),
});
export const SubscriptionRecord = IDL.Record({
  'principal' : IDL.Principal,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_devAdminGrant' : IDL.Func([], [], []),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteImage' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'generateImagePrompt' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeploymentUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getFileOwner' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
  'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
  'getKDPComplianceStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Bool)],
      ['query'],
    ),
  'getKDPValidationReport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(KDPValidation)],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getSubscription' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SubscriptionRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
  'listImages' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSubscription' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProject' : IDL.Func([Project], [], []),
  'validateKDP' : IDL.Func([IDL.Text], [IDL.Opt(KDPValidation)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Image = IDL.Record({
    'id' : IDL.Text,
    'dpi' : IDL.Float64,
    'owner' : IDL.Principal,
    'path' : IDL.Text,
    'projectId' : IDL.Text,
    'uploaded' : IDL.Int,
    'pageId' : IDL.Opt(IDL.Text),
  });
  const Dimensions = IDL.Record({
    'height' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const BleedSpec = IDL.Record({
    'top' : IDL.Float64,
    'left' : IDL.Float64,
    'bottom' : IDL.Float64,
    'right' : IDL.Float64,
  });
  const MarginSpec = IDL.Record({
    'top' : IDL.Float64,
    'left' : IDL.Float64,
    'bottom' : IDL.Float64,
    'right' : IDL.Float64,
  });
  const KDPValidation = IDL.Record({
    'errors' : IDL.Vec(IDL.Text),
    'trimSize' : Dimensions,
    'warnings' : IDL.Vec(IDL.Text),
    'bleed' : BleedSpec,
    'margin' : MarginSpec,
    'spineWidth' : IDL.Float64,
    'isValid' : IDL.Bool,
  });
  const Size = IDL.Record({ 'height' : IDL.Float64, 'width' : IDL.Float64 });
  const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const Layout = IDL.Record({ 'size' : Size, 'position' : Position });
  const CoverElement = IDL.Record({
    'text' : IDL.Text,
    'layout' : Layout,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const SpineSpec = IDL.Record({ 'text' : IDL.Text, 'width' : IDL.Float64 });
  const CoverSpec = IDL.Record({
    'front' : CoverElement,
    'back' : CoverElement,
    'spine' : SpineSpec,
    'bleed' : BleedSpec,
    'dimensions' : Dimensions,
  });
  const ProjectSettings = IDL.Record({
    'font' : IDL.Text,
    'margin' : IDL.Float64,
    'fontSize' : IDL.Float64,
    'lineSpacing' : IDL.Float64,
  });
  const ImagePosition = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const TextPosition = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const PageLayout = IDL.Record({
    'imagePosition' : ImagePosition,
    'textPosition' : TextPosition,
  });
  const Page = IDL.Record({
    'text' : IDL.Text,
    'pageNumber' : IDL.Nat,
    'layout' : PageLayout,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'kdpValidation' : KDPValidation,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'cover' : CoverSpec,
    'updatedAt' : IDL.Int,
    'story' : IDL.Text,
    'settings' : ProjectSettings,
    'pages' : IDL.Vec(Page),
  });
  const SubscriptionRecord = IDL.Record({
    'principal' : IDL.Principal,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_devAdminGrant' : IDL.Func([], [], []),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteImage' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'generateImagePrompt' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeploymentUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getFileOwner' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
    'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
    'getKDPComplianceStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Bool)],
        ['query'],
      ),
    'getKDPValidationReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(KDPValidation)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getSubscription' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SubscriptionRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
    'listImages' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSubscription' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProject' : IDL.Func([Project], [], []),
    'validateKDP' : IDL.Func([IDL.Text], [IDL.Opt(KDPValidation)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };