/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Layout {
    size: Size;
    position: Position;
}
export interface KDPValidation {
    errors: Array<string>;
    trimSize: Dimensions;
    warnings: Array<string>;
    bleed: BleedSpec;
    margin: MarginSpec;
    spineWidth: number;
    isValid: boolean;
}
export interface Dimensions {
    height: number;
    width: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CoverElement {
    text: string;
    layout: Layout;
    imageUrl?: string;
}
export interface Size {
    height: number;
    width: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TextPosition {
    x: number;
    y: number;
    height: number;
    width: number;
}
export interface ProjectSettings {
    font: string;
    margin: number;
    fontSize: number;
    lineSpacing: number;
}
export interface ImagePosition {
    x: number;
    y: number;
    height: number;
    width: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CoverSpec {
    front: CoverElement;
    back: CoverElement;
    spine: SpineSpec;
    bleed: BleedSpec;
    dimensions: Dimensions;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MarginSpec {
    top: number;
    left: number;
    bottom: number;
    right: number;
}
export interface Position {
    x: number;
    y: number;
}
export interface Page {
    text: string;
    pageNumber: bigint;
    layout: PageLayout;
    imageUrl?: string;
}
export interface BleedSpec {
    top: number;
    left: number;
    bottom: number;
    right: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Image {
    id: string;
    dpi: number;
    owner: Principal;
    path: string;
    projectId: string;
    uploaded: bigint;
    pageId?: string;
}
export interface PageLayout {
    imagePosition: ImagePosition;
    textPosition: TextPosition;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface Project {
    id: string;
    kdpValidation: KDPValidation;
    title: string;
    owner: Principal;
    createdAt: bigint;
    cover: CoverSpec;
    updatedAt: bigint;
    story: string;
    settings: ProjectSettings;
    pages: Array<Page>;
}
export interface SpineSpec {
    text: string;
    width: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addImage(projectId: string, path: string, dpi: number): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(title: string): Promise<bigint>;
    deleteImage(id: string): Promise<void>;
    deleteProject(id: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    generateImagePrompt(projectId: string, pageText: string, projectContext: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDeploymentUrl(): Promise<string>;
    getFileReference(path: string): Promise<FileReference>;
    getImage(id: string): Promise<Image | null>;
    getKDPComplianceStatus(projectId: string): Promise<boolean | null>;
    getKDPValidationReport(projectId: string): Promise<KDPValidation | null>;
    getProject(id: string): Promise<Project | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    listImages(projectId: string): Promise<Array<Image>>;
    listProjects(): Promise<Array<Project>>;
    registerFileReference(path: string, hash: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateProject(project: Project): Promise<void>;
    validateKDP(projectId: string): Promise<KDPValidation | null>;
}
import type { BleedSpec as _BleedSpec, CoverElement as _CoverElement, CoverSpec as _CoverSpec, Dimensions as _Dimensions, Image as _Image, KDPValidation as _KDPValidation, Layout as _Layout, Page as _Page, PageLayout as _PageLayout, Project as _Project, ProjectSettings as _ProjectSettings, SpineSpec as _SpineSpec, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addImage(arg0: string, arg1: string, arg2: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addImage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImage(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return result;
        }
    }
    async deleteImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImage(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async generateImagePrompt(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateImagePrompt(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateImagePrompt(arg0, arg1, arg2);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDeploymentUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeploymentUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeploymentUrl();
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getImage(arg0: string): Promise<Image | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImage(arg0);
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImage(arg0);
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getKDPComplianceStatus(arg0: string): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKDPComplianceStatus(arg0);
                return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKDPComplianceStatus(arg0);
            return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getKDPValidationReport(arg0: string): Promise<KDPValidation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKDPValidationReport(arg0);
                return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKDPValidationReport(arg0);
            return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProject(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async listImages(arg0: string): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.listImages(arg0);
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listImages(arg0);
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(to_candid_Project_n30(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(to_candid_Project_n30(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async validateKDP(arg0: string): Promise<KDPValidation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateKDP(arg0);
                return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateKDP(arg0);
            return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
        }
    }
}
function from_candid_CoverElement_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoverElement): CoverElement {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_CoverSpec_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoverSpec): CoverSpec {
    return from_candid_record_n22(uploadFile, downloadFile, value);
}
function from_candid_Image_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Image): Image {
    return from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_Page_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n27(uploadFile, downloadFile, value);
}
function from_candid_Project_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Image]): Image | null {
    return value.length === 0 ? null : from_candid_Image_n14(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KDPValidation]): KDPValidation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n19(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dpi: number;
    owner: Principal;
    path: string;
    projectId: string;
    uploaded: bigint;
    pageId: [] | [string];
}): {
    id: string;
    dpi: number;
    owner: Principal;
    path: string;
    projectId: string;
    uploaded: bigint;
    pageId?: string;
} {
    return {
        id: value.id,
        dpi: value.dpi,
        owner: value.owner,
        path: value.path,
        projectId: value.projectId,
        uploaded: value.uploaded,
        pageId: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.pageId))
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    kdpValidation: _KDPValidation;
    title: string;
    owner: Principal;
    createdAt: bigint;
    cover: _CoverSpec;
    updatedAt: bigint;
    story: string;
    settings: _ProjectSettings;
    pages: Array<_Page>;
}): {
    id: string;
    kdpValidation: KDPValidation;
    title: string;
    owner: Principal;
    createdAt: bigint;
    cover: CoverSpec;
    updatedAt: bigint;
    story: string;
    settings: ProjectSettings;
    pages: Array<Page>;
} {
    return {
        id: value.id,
        kdpValidation: value.kdpValidation,
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        cover: from_candid_CoverSpec_n21(uploadFile, downloadFile, value.cover),
        updatedAt: value.updatedAt,
        story: value.story,
        settings: value.settings,
        pages: from_candid_vec_n25(uploadFile, downloadFile, value.pages)
    };
}
function from_candid_record_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    front: _CoverElement;
    back: _CoverElement;
    spine: _SpineSpec;
    bleed: _BleedSpec;
    dimensions: _Dimensions;
}): {
    front: CoverElement;
    back: CoverElement;
    spine: SpineSpec;
    bleed: BleedSpec;
    dimensions: Dimensions;
} {
    return {
        front: from_candid_CoverElement_n23(uploadFile, downloadFile, value.front),
        back: from_candid_CoverElement_n23(uploadFile, downloadFile, value.back),
        spine: value.spine,
        bleed: value.bleed,
        dimensions: value.dimensions
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    layout: _Layout;
    imageUrl: [] | [string];
}): {
    text: string;
    layout: Layout;
    imageUrl?: string;
} {
    return {
        text: value.text,
        layout: value.layout,
        imageUrl: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.imageUrl))
    };
}
function from_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    pageNumber: bigint;
    layout: _PageLayout;
    imageUrl: [] | [string];
}): {
    text: string;
    pageNumber: bigint;
    layout: PageLayout;
    imageUrl?: string;
} {
    return {
        text: value.text,
        pageNumber: value.pageNumber,
        layout: value.layout,
        imageUrl: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.imageUrl))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Page>): Array<Page> {
    return value.map((x)=>from_candid_Page_n26(uploadFile, downloadFile, x));
}
function from_candid_vec_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Image>): Array<Image> {
    return value.map((x)=>from_candid_Image_n14(uploadFile, downloadFile, x));
}
function from_candid_vec_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n19(uploadFile, downloadFile, x));
}
function to_candid_CoverElement_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoverElement): _CoverElement {
    return to_candid_record_n35(uploadFile, downloadFile, value);
}
function to_candid_CoverSpec_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoverSpec): _CoverSpec {
    return to_candid_record_n33(uploadFile, downloadFile, value);
}
function to_candid_Page_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Page): _Page {
    return to_candid_record_n38(uploadFile, downloadFile, value);
}
function to_candid_Project_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n31(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    kdpValidation: KDPValidation;
    title: string;
    owner: Principal;
    createdAt: bigint;
    cover: CoverSpec;
    updatedAt: bigint;
    story: string;
    settings: ProjectSettings;
    pages: Array<Page>;
}): {
    id: string;
    kdpValidation: _KDPValidation;
    title: string;
    owner: Principal;
    createdAt: bigint;
    cover: _CoverSpec;
    updatedAt: bigint;
    story: string;
    settings: _ProjectSettings;
    pages: Array<_Page>;
} {
    return {
        id: value.id,
        kdpValidation: value.kdpValidation,
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        cover: to_candid_CoverSpec_n32(uploadFile, downloadFile, value.cover),
        updatedAt: value.updatedAt,
        story: value.story,
        settings: value.settings,
        pages: to_candid_vec_n36(uploadFile, downloadFile, value.pages)
    };
}
function to_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    front: CoverElement;
    back: CoverElement;
    spine: SpineSpec;
    bleed: BleedSpec;
    dimensions: Dimensions;
}): {
    front: _CoverElement;
    back: _CoverElement;
    spine: _SpineSpec;
    bleed: _BleedSpec;
    dimensions: _Dimensions;
} {
    return {
        front: to_candid_CoverElement_n34(uploadFile, downloadFile, value.front),
        back: to_candid_CoverElement_n34(uploadFile, downloadFile, value.back),
        spine: value.spine,
        bleed: value.bleed,
        dimensions: value.dimensions
    };
}
function to_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    layout: Layout;
    imageUrl?: string;
}): {
    text: string;
    layout: _Layout;
    imageUrl: [] | [string];
} {
    return {
        text: value.text,
        layout: value.layout,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none()
    };
}
function to_candid_record_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    pageNumber: bigint;
    layout: PageLayout;
    imageUrl?: string;
}): {
    text: string;
    pageNumber: bigint;
    layout: _PageLayout;
    imageUrl: [] | [string];
} {
    return {
        text: value.text,
        pageNumber: value.pageNumber,
        layout: value.layout,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none()
    };
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Page>): Array<_Page> {
    return value.map((x)=>to_candid_Page_n37(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
