/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BleedSpec {
  'top' : number,
  'left' : number,
  'bottom' : number,
  'right' : number,
}
export interface CoverElement {
  'text' : string,
  'layout' : Layout,
  'imageUrl' : [] | [string],
}
export interface CoverSpec {
  'front' : CoverElement,
  'back' : CoverElement,
  'spine' : SpineSpec,
  'bleed' : BleedSpec,
  'dimensions' : Dimensions,
}
export interface Dimensions { 'height' : number, 'width' : number }
export interface FileReference { 'hash' : string, 'path' : string }
export interface Image {
  'id' : string,
  'dpi' : number,
  'owner' : Principal,
  'path' : string,
  'projectId' : string,
  'uploaded' : bigint,
  'pageId' : [] | [string],
}
export interface ImagePosition {
  'x' : number,
  'y' : number,
  'height' : number,
  'width' : number,
}
export interface KDPValidation {
  'errors' : Array<string>,
  'trimSize' : Dimensions,
  'warnings' : Array<string>,
  'bleed' : BleedSpec,
  'margin' : MarginSpec,
  'spineWidth' : number,
  'isValid' : boolean,
}
export interface Layout { 'size' : Size, 'position' : Position }
export interface MarginSpec {
  'top' : number,
  'left' : number,
  'bottom' : number,
  'right' : number,
}
export interface Page {
  'text' : string,
  'pageNumber' : bigint,
  'layout' : PageLayout,
  'imageUrl' : [] | [string],
}
export interface PageLayout {
  'imagePosition' : ImagePosition,
  'textPosition' : TextPosition,
}
export interface Position { 'x' : number, 'y' : number }
export interface Project {
  'id' : string,
  'kdpValidation' : KDPValidation,
  'title' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'cover' : CoverSpec,
  'updatedAt' : bigint,
  'story' : string,
  'settings' : ProjectSettings,
  'pages' : Array<Page>,
}
export interface ProjectSettings {
  'font' : string,
  'margin' : number,
  'fontSize' : number,
  'lineSpacing' : number,
}
export interface Size { 'height' : number, 'width' : number }
export interface SpineSpec { 'text' : string, 'width' : number }
export interface TextPosition {
  'x' : number,
  'y' : number,
  'height' : number,
  'width' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addImage' : ActorMethod<[string, string, number], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string], bigint>,
  'deleteImage' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'generateImagePrompt' : ActorMethod<[string, string, string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeploymentUrl' : ActorMethod<[], string>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getImage' : ActorMethod<[string], [] | [Image]>,
  'getKDPComplianceStatus' : ActorMethod<[string], [] | [boolean]>,
  'getKDPValidationReport' : ActorMethod<[string], [] | [KDPValidation]>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'listImages' : ActorMethod<[string], Array<Image>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProject' : ActorMethod<[Project], undefined>,
  'validateKDP' : ActorMethod<[string], [] | [KDPValidation]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];